<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Controlling widget size}
-->

### Warning: This document is a very rough work in progress

# Controlling widget size

htmlwidgets provides a rich mechanism for specifying the sizing behavior of your widgets. It is designed to allow you, the widget author, to easily specify reasonable default sizes for your widget, that can be overridden by widget users (if you permit it).

This sizing mechanism is designed to address the following design forces that affect the natural size of a widget:

1. **The kind of widget it is.** Some widgets may only be designed to look good at small, fixed sizes (like [sparklines](http://en.wikipedia.org/wiki/Sparkline)) while other widgets may want every pixel that can be spared (like [network graphs](http://christophergandrud.github.io/d3Network/)).
2. **The context into which the widget is rendered.** While a given widget might look great at 960px by 480px in an R Markdown document, the same widget would look silly at that size in the RStudio Viewer pane, which is typically one-quarter the size of a RStudio window.

## Terminology

**Size policy:** A size policy is a collection of metadata that allows htmlwidgets to determine the proper size of widget for each rendering context (RStudio Viewer pane, R Markdown document, external browser, etc.). A size policy can be created using the htmlwidgets package's `sizePolicy` function.

**Standalone:** A type of rendering context in which a static widget is rendered in its own dedicated HTML file, usually as a result of calling `print()` on a widget or simply calling a widget-generating function from the R console. Standalone rendering allows htmlwidgets to take control of the widget's padding and for the widget to fill the entire page. (If a rendering context involves knitr or Shiny then it cannot be standalone.)

**Default width/height:** A width/height preference that was not directly asked for by the user. When a width/height is directly asked for by the user, it takes top priority; whereas default width/height can be overridden by other policy attributes like `fill`.

**Fill:** Having the widget fill (well, minus padding) the entire viewport, whether it's RStudio's Viewer pane or an entire browser window, and resize when the viewport is resized.

## Writing a size policy

Call the `sizePolicy()` function and assign the result to the widget data object, using the name `sizePolicy`. The following (optional) arguments can be passed to the `sizePolicy` function:

**defaultWidth = NULL, defaultHeight = NULL**  
The default width and height for this widget. If not specified, the default value is 960px by 500px (though this is subject to change in future releases---provide a defaultWidth and defaultHeight explicitly if size stability is important to you!). This width and height will be ignored if the user explicitly provides a width and height.

**padding = NULL**  
A vector of numeric values (NB: must be actual numbers, not CSS distances like `"500px"`) that dictate the padding size of standalone pages.

**viewer.defaultWidth = NULL, viewer.defaultHeight = NULL**  
Overrides regular `defaultWidth`/`defaultHeight` for RStudio Viewer pane mode only. Essentially ignored if `viewer.fill = TRUE`.

**viewer.padding = NULL**  
Overrides `padding` for RStudio Viewer mode only.

**viewer.fill = TRUE**  
If `TRUE`, the widget should fill the RStudio Viewer window. When this is the case, `viewer.defaultWidth` and `viewer.defaultHeight` are ignored.

**browser.defaultWidth = NULL, browser.defaultHeight = NULL,
browser.padding = NULL, browser.fill = FALSE**  
Same as the `viewer.*` equivalents, but for standalone rendering in an external browser.

**knitr.defaultWidth = NULL, knitr.defaultHeight = NULL**  
Same as the `viewer.*` equivalents, but for rendering in a knitr or R Markdown document.

**knitr.figure = TRUE**  
If `TRUE` (as is the default), knitr's `fig.width` and `fig.height` directives should be used to derive the width of the widget (unless the user provided width and height explicitly). When `knit.figure` is `TRUE`, `knitr.defaultWidth` and `knitr.defaultHeight` are ignored.
